[project]
name = "first-django-project"
version = "0.1.0"
description = ""
authors = [
    {name = "Rustem Umerov",email = "rustem.umerov.00@yandex.ru"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django (>=6.0.3,<7.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.5.1"
black = "^26.3.1"
flake8 = "^7.3.0"
isort = "^8.0.1"
mypy = "^1.20.0"
django-stubs = "^6.0.2"

