# Generated by Django 6.0.3 on 2026-08-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_event"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Event",
        ),
    ]
