# Generated by Django 6.0.3 on 2026-10-06 09:42

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Название категории"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание категории"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Например: Главный офис, Техподдержка, Менеджер",
                        max_length=150,
                        verbose_name="Название",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Рабочий email для связи",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Фактический адрес офиса (необязательно)",
                        verbose_name="Адрес",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название продукта"),
                ),
                ("description", models.TextField(verbose_name="Описание продукта")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=catalog.models.Product.get_image_path,
                        verbose_name="Фото продукта",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["category", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="catalog_pro_name_f603c0_idx"),
                    models.Index(
                        fields=["category"], name="catalog_pro_categor_7c1c1f_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "category"), name="unique_product_in_category"
                    )
                ],
            },
        ),
    ]
