# Generated by Django 6.0.3 on 2026-04-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Например: Главный офис, Техподдержка, Менеджер",
                        max_length=150,
                        verbose_name="Название",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Рабочий email для связи",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Фактический адрес офиса (необязательно)",
                        verbose_name="Адрес",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ["name"],
            },
        ),
    ]
